In [2]:
import numpy as np

2.

Difficulty Level: L1

Q. Create a 1D array of numbers from 0 to 9

Desired output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arreglo = np.arange(0,10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3.

Difficulty Level: L1

Q. Create a 3×3 numpy array of all True’s

In [4]:
arreglo = np.full((3,3), True)
arreglo

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4.
Difficulty Level: L1

Q. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

#> array([1, 3, 5, 7, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numeros_impares = arr[arr % 2 != 0]
numeros_impares


array([1, 3, 5, 7, 9])

5.
Difficulty Level: L1

Q. Replace all odd numbers in arr with -1

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Desired Output:

#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [7]:
sin_impares = arr.copy()
sin_impares[sin_impares % 2 != 0] = -1
sin_impares

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6.
Difficulty Level: L2

Q. Replace all odd numbers in arr with -1 without changing arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

out
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

arr
#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
sin_impares

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7.
Difficulty Level: L1

Q. Convert a 1D array to a 2D array with 2 rows

Input:

np.arange(10)

#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired Output:

#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9]])

In [9]:
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
array = array.reshape(2, -1)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8.
Difficulty Level: L2

Q. Stack arrays a and b vertically

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:


#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9],

#>        [1, 1, 1, 1, 1],

#>        [1, 1, 1, 1, 1]])

In [11]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
b = np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
pila_vertical = np.vstack((a, b))
pila_vertical

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9.
Difficulty Level: L2

Q. Stack the arrays a and b horizontally.

Input

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],

#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [14]:
pila_horizontal = np.hstack((a, b))
pila_horizontal

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10.
Difficulty Level: L2

Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`

Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [20]:
a = np.array([1,2,3])
patron = np.concatenate((np.repeat(a, 3), np.tile(a, 3)))
patron

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])