In [2]:
import numpy as np

2. Crear una  matriz de una dimensión con números del 0 al 9.

Salida esperada:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [3]:
arreglo = np.arange(0,10)
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Crear una matriz de 3x3 en la que todos los valores sean True.


In [4]:
arreglo = np.full((3,3), True)
arreglo

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. Extraer todos los números impares del siguiente arreglo:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Salida esperada: array([1, 3, 5, 7, 9])


In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numeros_impares = arr[arr % 2 != 0]
numeros_impares


array([1, 3, 5, 7, 9])

5. Reemplazar todos los números impares en el arreglo anterior con -1.

Salida esperada: array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])


In [7]:
sin_impares = arr.copy()
sin_impares[sin_impares % 2 != 0] = -1
sin_impares

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. Reemplazar todos los números impares en el arreglo con -1 sin modificar el arreglo.

Salida esperada: 

salida: array([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

arr = ([0, -1, 2, -1, 4, -1, 6, -1, 8, -1])


In [8]:
sin_impares

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

7. Convertir una matriz de una dimensión en una de dos dimensiones con dos filas.

Entrada: np.arrange(10)

Salida esperada: array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])


In [10]:
array = np.arange(10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array = array.reshape(2, -1)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. Apilar las matrices a y b de manera vertical.

Entradas:

a = np.arangE(10).reshape(2,-1)

b = np.repeat(1,10).reshape(2,-1)

Salida esperada:

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [12]:
a = np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b = np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
pila_vertical = np.vstack((a, b))
pila_vertical

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. Apilar las matrices a y b del ejercicio anterior de manera horizontal.

Salida esperada:

array([[0, 1, 2, 3, 4, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1 ,1]])


In [15]:
pila_horizontal = np.hstack((a, b))
pila_horizontal

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. Crear el siguiente patrón sin codificación. Utilizar solo funciones de numpy y la siguiente matriz de entrada a.

Entrada: a = np.array([1, 2, 3])

Salida esperada: 

array ([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [16]:
a = np.array([1,2,3])
patron = np.concatenate((np.repeat(a, 3), np.tile(a, 3)))
patron

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])